### ISSUE TITLE
text color

### ISSUE THREAD

**Issue by AmirhN1382** [rezaaa/biainobokhor#1]
not sure if it's a bug or a feature, but the text color is too close to the background colors and it's literally invisible. some people might think their token is not pasted at all.
![screenshot_5665_2022-09-02_00 57 20](https://user-images.githubusercontent.com/68735480/188006127-2773aebd-20e1-43a6-9320-c0fe0be60391.png)

**Comment by AmirhN1382** [comment]
+ a dark mode would be cool

**Comment by rezaaa** [comment]
I think the input color issue is because of the dark mode settings. I'll fix it.
